package com.careflow.appointments;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import java.time.OffsetDateTime;
import java.util.*;
@RestController @RequestMapping("/api/v1/appointments")
public class AppointmentController {
 private final JdbcTemplate db; private final AppointmentEventPublisher events; public AppointmentController(JdbcTemplate db,AppointmentEventPublisher events){this.db=db;this.events=events;}
 public record Booking(@NotNull UUID doctorId,@NotNull @Future OffsetDateTime startsAt,@NotNull @Future OffsetDateTime endsAt,@Size(max=240) String reason,@NotNull Type appointmentType){}
 public record Reschedule(@NotNull @Future OffsetDateTime startsAt,@NotNull @Future OffsetDateTime endsAt){}
 public enum Type{IN_PERSON,VIDEO,PHONE}
 @GetMapping @PreAuthorize("hasRole('PATIENT')") public List<Map<String,Object>> mine(org.springframework.security.core.Authentication auth){return db.queryForList("SELECT a.id,a.doctor_id AS \"doctorId\",a.starts_at AS \"startsAt\",a.ends_at AS \"endsAt\",a.status,a.appointment_type AS \"appointmentType\",a.reason FROM appointments a JOIN users u ON u.id=a.patient_id WHERE u.email=? ORDER BY a.starts_at DESC LIMIT 100",auth.getName());}
 @PostMapping @PreAuthorize("hasRole('PATIENT')") @Transactional public Map<String,Object> book(@Valid @RequestBody Booking b,org.springframework.security.core.Authentication auth){if(!b.endsAt().isAfter(b.startsAt())||b.endsAt().isAfter(b.startsAt().plusHours(3)))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Appointment duration is invalid");try{var patient=db.queryForObject("SELECT id FROM users WHERE email=? AND role='PATIENT' AND active=TRUE",UUID.class,auth.getName());if(patient==null)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Patient account required");UUID id=UUID.randomUUID();int inserted=db.update("INSERT INTO appointments(id,patient_id,doctor_id,starts_at,ends_at,status,appointment_type,reason) SELECT ?,?,d.user_id,?,?, 'BOOKED', ?, ? FROM doctor_profiles d JOIN users u ON u.id=d.user_id WHERE d.user_id=? AND u.active=TRUE",id,patient,b.startsAt(),b.endsAt(),b.appointmentType().name(),b.reason(),b.doctorId());if(inserted==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Doctor not found");db.update("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES(?, 'APPOINTMENT_CREATED','APPOINTMENT',?,jsonb_build_object('source','api'))",patient,id);events.publish("APPOINTMENT_CREATED",id,patient,b.doctorId());return Map.of("id",id,"status","BOOKED","startsAt",b.startsAt(),"endsAt",b.endsAt());}catch(org.springframework.dao.DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"That appointment time is no longer available");}}
 @PostMapping("/{id}/cancel") @Transactional public void cancel(@PathVariable UUID id,org.springframework.security.core.Authentication auth){int updated=db.update("UPDATE appointments a SET status='CANCELLED',updated_at=now() FROM users u WHERE a.patient_id=u.id AND u.email=? AND a.id=? AND a.status IN ('BOOKED','CONFIRMED')",auth.getName(),id);if(updated==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Appointment not found or cannot be cancelled");}
 @PutMapping("/{id}/reschedule") @PreAuthorize("hasRole('PATIENT')") @Transactional public Map<String,Object> reschedule(@PathVariable UUID id,@Valid @RequestBody Reschedule request,org.springframework.security.core.Authentication auth){if(!request.endsAt().isAfter(request.startsAt())||request.endsAt().isAfter(request.startsAt().plusHours(3)))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Appointment duration is invalid");try{UUID patient=db.queryForObject("SELECT id FROM users WHERE email=? AND role='PATIENT'",UUID.class,auth.getName());UUID doctor=db.queryForObject("SELECT doctor_id FROM appointments WHERE id=? AND patient_id=? AND status IN ('BOOKED','CONFIRMED')",UUID.class,id,patient);db.update("UPDATE appointments SET starts_at=?,ends_at=?,status='BOOKED',updated_at=now() WHERE id=?",request.startsAt(),request.endsAt(),id);events.publish("APPOINTMENT_RESCHEDULED",id,patient,doctor);return Map.of("id",id,"status","BOOKED","startsAt",request.startsAt(),"endsAt",request.endsAt());}catch(org.springframework.dao.DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"That appointment time is no longer available");}catch(org.springframework.dao.EmptyResultDataAccessException e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Appointment not found");}}
}
