package com.careflow.doctors;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import java.util.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.sql.Time;
@RestController @RequestMapping("/api/v1/doctors")
public class DoctorController {
 private final JdbcTemplate db; public DoctorController(JdbcTemplate db){this.db=db;}
 @GetMapping public Map<String,Object> list(@RequestParam(defaultValue="") String q,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="12") int size,@RequestParam(defaultValue="") String department){int safePage=Math.max(0,page),safeSize=Math.min(50,Math.max(1,size));String term="%"+q.trim()+"%";String dep="%"+department.trim()+"%";var items=db.query("SELECT u.id, u.first_name, u.last_name, d.specialty, d.location, d.rating, COALESCE(string_agg(dep.name, ', '),'') AS department FROM doctor_profiles d JOIN users u ON u.id=d.user_id LEFT JOIN doctor_departments dd ON dd.doctor_id=d.user_id LEFT JOIN departments dep ON dep.id=dd.department_id WHERE u.active=TRUE AND (concat(u.first_name,' ',u.last_name) ILIKE ? OR d.specialty ILIKE ?) AND COALESCE(dep.name,'') ILIKE ? GROUP BY u.id,d.specialty,d.location,d.rating ORDER BY u.last_name,u.first_name LIMIT ? OFFSET ?",(rs,n)->Map.of("id",rs.getObject("id"),"firstName",rs.getString("first_name"),"lastName",rs.getString("last_name"),"specialty",rs.getString("specialty"),"location",Objects.toString(rs.getString("location"),""),"rating",rs.getBigDecimal("rating"),"department",rs.getString("department")),term,term,dep,safeSize,safePage*safeSize);return Map.of("content",items,"page",safePage,"size",safeSize,"hasMore",items.size()==safeSize);}
 @GetMapping("/{id}") public Map<String,Object> get(@PathVariable UUID id){try{return db.queryForMap("SELECT u.id,u.first_name AS \"firstName\",u.last_name AS \"lastName\",d.specialty,d.bio,d.location,d.rating FROM doctor_profiles d JOIN users u ON u.id=d.user_id WHERE u.id=? AND u.active=TRUE",id);}catch(org.springframework.dao.EmptyResultDataAccessException e){throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"Doctor not found");}}
 @GetMapping("/{id}/availability") public Map<String,Object> availability(@PathVariable UUID id,@RequestParam LocalDate date){var rows=db.query("SELECT starts_at,ends_at,slot_minutes FROM doctor_availability WHERE doctor_id=? AND day_of_week=EXTRACT(ISODOW FROM CAST(? AS date))::int AND active=TRUE ORDER BY starts_at",(rs,n)->new Object[]{rs.getTime(1).toLocalTime(),rs.getTime(2).toLocalTime(),rs.getInt(3)},id,date);if(rows.isEmpty())return Map.of("doctorId",id,"date",date,"slots",List.of());List<String> slots=new ArrayList<>();for(Object[] row:rows){var start=(java.time.LocalTime)row[0];var end=(java.time.LocalTime)row[1];int minutes=(int)row[2];while(!start.plusMinutes(minutes).isAfter(end)){LocalDateTime slot=date.atTime(start);boolean occupied=Boolean.TRUE.equals(db.queryForObject("SELECT EXISTS(SELECT 1 FROM appointments WHERE doctor_id=? AND status IN ('BOOKED','CONFIRMED') AND starts_at < ? AND ends_at > ?)",Boolean.class,id,slot.plusMinutes(minutes).atOffset(java.time.ZoneOffset.UTC),slot.atOffset(java.time.ZoneOffset.UTC)));if(!occupied&&!slot.isBefore(LocalDateTime.now(java.time.ZoneOffset.UTC)))slots.add(slot.toString());start=start.plusMinutes(minutes);}}return Map.of("doctorId",id,"date",date,"slots",slots);}
}
