package com.careflow.documents;
import jakarta.validation.constraints.NotBlank;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;
import java.io.IOException;
import java.util.*;
@RestController @RequestMapping("/api/v1/documents")
public class DocumentController {
 private static final long MAX_SIZE=10L*1024*1024; private final JdbcTemplate db;private final ObjectStorage storage;
 public DocumentController(JdbcTemplate db,ObjectStorage storage){this.db=db;this.storage=storage;}
 @GetMapping @PreAuthorize("hasAnyRole('PATIENT','DOCTOR','ADMIN')") public List<Map<String,Object>> list(org.springframework.security.core.Authentication auth){return db.queryForList("SELECT m.id,m.patient_id AS \"patientId\",m.uploaded_by AS \"uploadedBy\",m.file_name AS \"fileName\",m.file_type AS \"fileType\",m.file_size AS \"fileSize\",m.created_at AS \"createdAt\" FROM medical_documents m JOIN users viewer ON viewer.email=? WHERE viewer.role='ADMIN' OR (viewer.role='PATIENT' AND m.patient_id=viewer.id) OR (viewer.role='DOCTOR' AND EXISTS(SELECT 1 FROM appointments a WHERE a.patient_id=m.patient_id AND a.doctor_id=viewer.id)) ORDER BY m.created_at DESC",auth.getName());}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasRole('PATIENT')") @Transactional public Map<String,Object> upload(@RequestPart("file") MultipartFile file,@RequestPart("title") @NotBlank String title,org.springframework.security.core.Authentication auth){if(file.isEmpty()||file.getSize()>MAX_SIZE)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"File must be between 1 byte and 10 MB");String filename=Optional.ofNullable(file.getOriginalFilename()).orElse("demo-document.pdf");if(!filename.toLowerCase(Locale.ROOT).endsWith(".pdf")||!MediaType.APPLICATION_PDF_VALUE.equalsIgnoreCase(file.getContentType()))throw new ResponseStatusException(HttpStatus.UNSUPPORTED_MEDIA_TYPE,"Only PDF demo documents are accepted");try{byte[] bytes=file.getBytes();if(bytes.length<5||bytes[0]!='%'||bytes[1]!='P'||bytes[2]!='D'||bytes[3]!='F'||bytes[4]!='-')throw new ResponseStatusException(HttpStatus.UNSUPPORTED_MEDIA_TYPE,"The file does not contain a PDF signature");UUID patient=db.queryForObject("SELECT id FROM users WHERE email=? AND role='PATIENT' AND active=TRUE",UUID.class,auth.getName());UUID id=UUID.randomUUID();String key="patients/"+patient+"/"+id+".pdf";storage.put(key,new java.io.ByteArrayInputStream(bytes),bytes.length,MediaType.APPLICATION_PDF_VALUE);try{db.update("INSERT INTO medical_documents(id,patient_id,uploaded_by,file_name,file_type,file_size,storage_key) VALUES(?,?,?,?,?,?,?)",id,patient,patient,filename.replaceAll("[\\r\\n]",""),MediaType.APPLICATION_PDF_VALUE,bytes.length,key);db.update("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) VALUES(?, 'DOCUMENT_UPLOADED','DOCUMENT',?,jsonb_build_object('fileType','application/pdf'))",patient,id);}catch(RuntimeException e){storage.delete(key);throw e;}return Map.of("id",id,"fileName",filename,"title",title,"fileType",MediaType.APPLICATION_PDF_VALUE,"fileSize",bytes.length,"createdAt",java.time.Instant.now());}catch(IOException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Unable to read uploaded file");}}
 @GetMapping("/{id}/download") @PreAuthorize("hasAnyRole('PATIENT','DOCTOR','ADMIN')") public ResponseEntity<byte[]> download(@PathVariable UUID id,org.springframework.security.core.Authentication auth){var rows=db.query("SELECT m.storage_key,m.file_name,m.patient_id FROM medical_documents m JOIN users viewer ON viewer.email=? WHERE m.id=? AND (viewer.role='ADMIN' OR (viewer.role='PATIENT' AND m.patient_id=viewer.id) OR (viewer.role='DOCTOR' AND EXISTS(SELECT 1 FROM appointments a WHERE a.patient_id=m.patient_id AND a.doctor_id=viewer.id)))",(rs,n)->new Object[]{rs.getString(1),rs.getString(2),rs.getObject(3,UUID.class)},auth.getName(),id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Document not found");Object[] row=rows.getFirst();byte[] bytes=storage.get((String)row[0]);db.update("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata) SELECT id,'DOCUMENT_DOWNLOADED','DOCUMENT',?, '{}'::jsonb FROM users WHERE email=?",id,auth.getName());String safe=row[1].toString().replaceAll("[\\r\\n\\\"]","_");return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,org.springframework.http.ContentDisposition.attachment().filename(safe).build().toString()).body(bytes);}
 @DeleteMapping("/{id}") @PreAuthorize("hasAnyRole('PATIENT','ADMIN')") @Transactional public void delete(@PathVariable UUID id,org.springframework.security.core.Authentication auth){var rows=db.query("SELECT m.storage_key FROM medical_documents m JOIN users viewer ON viewer.email=? WHERE m.id=? AND (viewer.role='ADMIN' OR (viewer.role='PATIENT' AND m.patient_id=viewer.id))",(rs,n)->rs.getString(1),auth.getName(),id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Document not found");db.update("DELETE FROM medical_documents WHERE id=?",id);storage.delete(rows.getFirst());}
}
